### ISSUE TITLE
lit-demo installation on Ubuntu not fully complete

### ISSUE THREAD

**Issue by spapastamkou** [C2DH/playing-ranke-two-stack#1]
Hi there. I am on Ubuntu 22.04.1 LTS (Jammy Jellyfish) and when on the following step: https://github.com/C2DH/playing-ranke-two-stack#open-web-app-and-start-playing I do not manage to have the complete application. I leave here the log after docker-compose up (that looks ok) 
[uni@udocker-compose-up.txt_29082022.txt](https://github.com/C2DH/playing-ranke-two-stack/files/9445435/uni%40udocker-compose-up.txt_29082022.txt)
and two screenshots of localhost:8088 taken on Firefox and Chrome after I tried to run [lit-demo](https://github.com/uzh/lit-demo/tree/69fb3c82a44ca78875afe06d11d8e6c9f664376b) (note that I had previously done [this step](https://github.com/C2DH/playing-ranke-two-stack#install-an-existing-game))
[screenshot-topics-chrome_29082022.odt](https://github.com/C2DH/playing-ranke-two-stack/files/9445440/screenshot-topics-chrome_29082022.odt)
[screenshot-topics_29082022.odt](https://github.com/C2DH/playing-ranke-two-stack/files/9445441/screenshot-topics_29082022.odt)
where you can see the missing buttons. Thanks a lot for your help.

**Comment by yaslena** [comment]
It looks like the game-importing step didn't work properly (https://github.com/C2DH/playing-ranke-two-stack#import-game-data).
To test if that is indeed the case, try running the shell again (while the web, backend, and database containers are still running) with:
```docker-compose run shell```
and then use the list-topics command inside the shell:
```marugoto:>list-topics```

If the output is an empty screen, then the import didn't work.

**Comment by spapastamkou** [comment]
This is now resolved after repeating the process again and especially after [the `do-import` step](https://github.com/C2DH/playing-ranke-two-stack#import-game-data) which was what had not worked initially. I close this issue.
