### ISSUE TITLE
missing images and media files in web app

### ISSUE THREAD

**Issue by yaslena** [C2DH/playing-ranke-two-stack#2]
After you launch the web app on http://localhost:8088 and log into the application to start playing, you may experience that most, or all of the images and media files are not displayed properly because they are not loaded:
<img width="600" alt="Screenshot 2022-07-11 at 15 11 06" src="https://user-images.githubusercontent.com/53467834/187377431-a0fa4d8a-c959-4735-94f0-b662597d4e8a.png">

There is no elegant way to fix this yet, but you can try this workaround:

1. Open a page with a missing image in your game in your browser. Right-click on the image and select "inspect". The browser console will open and you will see the html text that reveals the structure of the web page. The **image source** (<img src="") should already be highlighted as shown in the screenshot below:

<img width="1200" alt="Screenshot 2022-08-30 at 10 09 55" src="https://user-images.githubusercontent.com/53467834/187385632-112de6e4-9c61-4348-af38-280f03192895.png">

Take note of the part that comes before /image/... In this example, it is "**my-demo**". In most cases, but not always, it will be the game alias that you chose when importing files with the do-import command in the shell.

2. After you have imported files with the shell's *do-import* command, locate the automatically created **hidden folder** (filename starting with a dot) that corresponds to the game you imported (you can show hidden folders by pressing *command - shift - dot*).  It should be located in the same directory as the original game files.
3. Open the resources folder within the hidden folder and **copy all of its content**. This will include all the images, text files, audio files, video files, and alternative image files for thumbnail images.
4. Go to the **non-hidden** folder of your game and open the resources folder there. Create 3 subfolders within it: "image", "audio", and "video". Now paste all the image and text files from the hidden folder (JPG, PNG, PDF, docx ect.) into the "image" folder. Audio files (mp3) go into the "audio" folder, and video files (mp4) go into the "video" folder. 
**Note**: Do not delete the media files from the original resources folder, otherwise the references within the game will no longer work and the game will break. You can either change all the media references in the game or just have duplicate files in your resources folder and its subfolders.
5. Run the "do-import" command again to get the files with the new folder structure into the container and the hidden game folder.
6. Now you need to modify the docker-compose.yml. 
**Note**: Every time you modify the docker-compose.yml, in order for the changes to take effect, you need to docker-compose down to stop the containers and then docker-compose up again after the changes are made. 
Now open the docker-compose.yml file and add a new volume to the web section.
Right under this line:
```
web:
    image: c2dhunilu/marugoto-frontend:latest
    volumes:
      - ./data/marugoto/contents/ranketwo/resources:/usr/share/nginx/html/ranketwo
```
you should add:
```
 - ./data/marugoto/contents/"original-game-name"/resources:/usr/share/nginx/html/"name-from-browser-console"
```
In our example we would add:
```
 - ./data/marugoto/contents/lit-demo/resources:/usr/share/nginx/html/my-demo
```
7. Restart the containers with docker-compose up again and open the web app in the browser http://localhost:8088. The images should be displayed now. Make sure to delete the cash in your browser to refresh the page. You can also right-click on the image and reload it.
**Note**: You can add these individual volume configurations to your docker-compose.override.yml (which will be gitignored). Just duplicate the existing docker-compose.yml file, rename it into "docker-compose.override.yml" and add the extra volumes there.

**Comment by spapastamkou** [comment]
Thanks for opening the issue @yaslena

**Comment by eliselavy** [comment]
@yaslena workaround tested but for the lit-demo project still problem with the images. 
The path is: `<img src="/my-demo/image/114_Edo1849_PublicDomain_1360x1109.jpg">` but in the image's name is: `1.1.4_Edo1849_PublicDomain.jpg` https://github.com/uzh/lit-demo/blob/69fb3c82a44ca78875afe06d11d8e6c9f664376b/resources/1.1.4_Edo1849_PublicDomain.jpg


Workaround for ranketwo without copying  resources folder structure


 ```
 web:
    image: c2dhunilu/marugoto-frontend:latest
    volumes:
      - ./data/marugoto/contents/ranketwo/resources:/usr/share/nginx/html/esources
```

**Comment by yaslena** [comment]
@eliselavy Yes, that is correct. Daniele had already changed all the game-internal media file references for ranketwo and created the folder structure with subfolders:-)

As for the lit-demo game:
The `1.1.4_Edo1849_PublicDomain.jpg` is the file name of the image in the original lit-demo folder.
If you check the resource folder in the **hidden game-folder**, you will see that it contains 
both files:
- `1.1.4_Edo1849_PublicDomain.jpg`
- `114_Edo1849_PublicDomain_1360x1109.jpg`
<img width="361" alt="Screenshot 2022-08-31 at 15 18 06" src="https://user-images.githubusercontent.com/53467834/187687638-68887351-c186-438e-b1be-f071fe577bbe.png">

You definitely need the files from the **hidden folder** for this to work, as described above in steps 2-3, because only this folder contains the "alternative image files for thumbnail images".
If you do this, the images should be displayed properly:

<img width="600" alt="Screenshot 2022-08-31 at 15 26 13" src="https://user-images.githubusercontent.com/53467834/187689361-d3d49d7a-8596-4627-b76a-6ad2576ff45c.png">

**Comment by yaslena** [comment]
I have created a new volume in the shell section of the docker-compose.yml. Now the copy-pasting of hidden files is no longer necessary. Closing this issue.
